### ISSUE TITLE
interaction,recommendation and item feature

### ISSUE THREAD

**Issue by CatOneTwo** [minxingzhang/MIARS#1]
Thanks for your great job, could you provide detailed data preprocessing code and interactions and recommendations file? Thank you!

**Comment by minxingzhang** [comment]
We will update the information about data processing later.

**Comment by CatOneTwo** [comment]
Thank you!

**Comment by Richardwarriors** [comment]
Thanks for your great job, could you provide detailed data preprocessing code? Also, I am confused about the definition of variable fr_vector_target , fr_target. Could you give me more detailed explanation? Thanks

**Comment by minxingzhang** [comment]
> Thanks for your great job, could you provide detailed data preprocessing code? Also, I am confused about the definition of variable fr_vector_target , fr_target. Could you give me more detailed explanation? Thanks

We have updated the instructions, trying to solve your concern, please check them in README.md.
